steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/first-renderer-260114/testing', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/first-renderer-260114/testing']